"use client";
import { useCallback, useEffect, useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import Image from "next/image";
import { normalizeBrandContent } from "../lib/brand";
import { Building2, ChevronRight, FileText, FolderKanban, Globe2, Home, ImagePlus, LayoutDashboard, LogOut, Newspaper, Plus, Save, Settings, Sparkles, Trash2, Wrench, X } from "lucide-react";

const sections = [
  { id: "home", label: "Home Page", icon: Home, single: true }, { id: "global", label: "Header & Footer", icon: Settings, single: true },
  { id: "pages", label: "Website Pages", icon: FileText }, { id: "services", label: "Services", icon: Wrench },
  { id: "projects", label: "Projects", icon: FolderKanban }, { id: "articles", label: "News Articles", icon: Newspaper }, { id: "offices", label: "Offices", icon: Building2 },
  { id: "trends", label: "AI & Industry Trends", icon: Sparkles },
];
const f=(name,label,type="text",group="Content")=>({name,label,type,group});
const fields = {
  global:[f("siteName","Website name"),f("tagline","Brand tagline"),f("email","Contact email","email","Contact"),f("phone","Phone number","text","Contact"),f("whatsappNumber","WhatsApp number (with country code)","text","Contact"),f("footerSummary","Footer description","textarea","Footer"),f("copyright","Copyright text","text","Footer"),f("navigation","Navigation links","json","Navigation")],
  home:[f("heroEyebrow","Hero eyebrow"),f("heroTitle","Hero heading"),f("heroHighlight","Highlighted heading"),f("heroDescription","Hero description","textarea"),f("heroImage","Hero background","image"),f("heroPrimaryLabel","Primary button label"),f("heroPrimaryHref","Primary button link"),f("heroSecondaryLabel","Secondary button label"),f("heroSecondaryHref","Secondary button link"),f("aboutEyebrow","About eyebrow","text","About"),f("aboutTitle","About heading","text","About"),f("aboutLead","About lead","textarea","About"),f("aboutBody","About description","textarea","About"),f("aboutImage","About image","image","About"),f("servicesEyebrow","Services eyebrow","text","Services"),f("servicesTitle","Services heading","text","Services"),f("projectsEyebrow","Projects eyebrow","text","Projects"),f("projectsTitle","Projects heading","text","Projects"),f("projectsDescription","Projects description","textarea","Projects"),f("industriesEyebrow","Industries eyebrow","text","Industries"),f("industriesTitle","Industries heading","text","Industries"),f("industriesDescription","Industries description","textarea","Industries"),f("trendsEyebrow","Trends eyebrow","text","AI trends"),f("trendsTitle","Trends heading","text","AI trends"),f("trendsDescription","Trends introduction","textarea","AI trends"),f("safetyEyebrow","Safety eyebrow","text","Safety"),f("safetyTitle","Safety heading","text","Safety"),f("safetyDescription","Safety description","textarea","Safety"),f("safetyImage","Safety image","image","Safety"),f("newsEyebrow","News eyebrow","text","News"),f("newsTitle","News heading","text","News"),f("newsDescription","News description","textarea","News"),f("contactEyebrow","Form eyebrow","text","Contact form"),f("contactTitle","Form heading","text","Contact form"),f("contactDescription","Form description","textarea","Contact form"),f("ctaEyebrow","CTA eyebrow","text","Footer CTA"),f("ctaTitle","CTA heading","text","Footer CTA"),f("ctaDescription","CTA description","textarea","Footer CTA"),f("ctaBackground","CTA background","image","Footer CTA")],
  pages:[f("title","Page name"),f("slug","URL slug"),f("heroEyebrow","Hero eyebrow","text","Hero"),f("heroTitle","Hero heading","text","Hero"),f("heroDescription","Hero description","textarea","Hero"),f("heroImage","Hero image","image","Hero"),f("sectionEyebrow","Intro eyebrow","text","Page intro"),f("sectionTitle","Intro heading","text","Page intro"),f("sectionDescription","Intro description","textarea","Page intro"),f("seoTitle","SEO title","text","Search engine"),f("seoDescription","SEO description","textarea","Search engine")],
  services:[f("title","Service title"),f("slug","URL slug"),f("summary","Card description","textarea"),f("body","Detailed content","textarea"),f("image","Service image","image"),f("points","Service points","json"),f("order","Display order","number"),f("featured","Show on homepage","boolean")],
  projects:[f("title","Project title"),f("slug","URL slug"),f("location","Location"),f("metric","Key metric"),f("summary","Summary","textarea"),f("details","Project details","textarea"),f("image","Project image","image"),f("order","Display order","number"),f("featured","Show on homepage","boolean")],
  articles:[f("title","Article title"),f("slug","URL slug"),f("category","Category"),f("excerpt","Excerpt","textarea"),f("content","Article content","textarea"),f("coverImage","Cover image","image"),f("publishedDate","Publish date","date"),f("externalUrl","External article URL","url"),f("featured","Featured article","boolean")],
  offices:[f("name","Office name"),f("address","Address","textarea"),f("email","Email","email"),f("phone","Phone"),f("mapUrl","Map URL","url"),f("order","Display order","number")],
  trends:[f("title","Card title"),f("slug","Slug"),f("description","Description","textarea"),f("image","Card image","image"),f("order","Display order","number"),f("featured","Show on homepage","boolean")]
};
const api=(path,options)=>fetch(`/api/admin/cms/${path}`,options);
const publicCmsUrl=(process.env.NEXT_PUBLIC_STRAPI_URL||"http://127.0.0.1:1337").replace(/\/$/,"");
async function responseData(response){
  const text=await response.text();
  if(!text)return {error:response.ok?"The CMS returned an empty response.":"The CMS could not process this request."};
  try{return normalizeBrandContent(JSON.parse(text))}catch{return {error:text||"The CMS returned an invalid response."}}
}
const titleOf=(item,section)=>item?.title||item?.name||item?.siteName||section.label;

export default function AdminDashboard(){
  const router=useRouter(); const [active,setActive]=useState(sections[0]); const [items,setItems]=useState([]); const [selected,setSelected]=useState(null);
  const [form,setForm]=useState({}); const [loading,setLoading]=useState(true); const [saving,setSaving]=useState(false); const [notice,setNotice]=useState(""); const [mobileNav,setMobileNav]=useState(false);
  const load=useCallback(async(section)=>{setLoading(true);setNotice("");try{const response=await api(`content/${section.id}`);if(response.status===401){router.replace("/admin/login");return;}const data=await responseData(response);if(!response.ok){setNotice(data.error?.message||data.error||"Could not load content.");return;}const list=section.single?[data].filter(Boolean):(Array.isArray(data)?data:[]);setItems(list);setSelected(list[0]||null);setForm(list[0]||{});}catch{setNotice("The CMS is temporarily unavailable. Please try again.");}finally{setLoading(false)}},[router]);
  useEffect(()=>{const timer=setTimeout(()=>load(active),0);return()=>clearTimeout(timer)},[active,load]);
  const groups=useMemo(()=>Object.entries((fields[active.id]||[]).reduce((all,field)=>({...all,[field.group]:[...(all[field.group]||[]),field]}),{})),[active]);
  function choose(item){setSelected(item);setForm(item||{});setNotice("");}
  function createNew(){setSelected(null);setForm(active.id==="articles"?{featured:false,publishedDate:new Date().toISOString().slice(0,10)}:{featured:true,order:items.length});}
  async function save(){setSaving(true);setNotice("");const prepared={};for(const field of fields[active.id]){let value=form[field.name];if(field.type==="json"&&typeof value==="string"){try{value=JSON.parse(value)}catch{setNotice(`${field.label} contains invalid JSON.`);setSaving(false);return;}}if(field.type==="image"&&value?.id)value=value.id;prepared[field.name]=value===""?null:value;}
    try{const path=`content/${active.id}${selected?.documentId?`/${selected.documentId}`:""}`;const response=await api(path,{method:selected?.documentId?"PUT":"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({data:prepared})});const data=await responseData(response);if(response.status===401){router.replace("/admin/login");return;}if(!response.ok){setNotice(data.error?.message||data.error||"Could not save changes.");return;}setNotice("Changes saved and published.");await load(active);}catch{setNotice("The CMS is temporarily unavailable. Please try again.");}finally{setSaving(false)}}
  async function remove(){if(!selected?.documentId||!window.confirm(`Delete ${titleOf(selected,active)}?`))return;await api(`content/${active.id}/${selected.documentId}`,{method:"DELETE"});await load(active);}
  async function upload(field,file){if(!file)return;setNotice("Uploading image…");try{const body=new FormData();body.append("files",file);const response=await api("upload",{method:"POST",body});const media=await responseData(response);if(response.ok){setForm((current)=>({...current,[field.name]:media}));setNotice("Image uploaded. Save changes to publish it.");}else setNotice(media.error?.message||media.error||"Image upload failed.");}catch{setNotice("The CMS is temporarily unavailable. Please try again.");}}
  async function logout(){await fetch("/api/admin/logout",{method:"POST"});router.replace("/admin/login");}
  return <main className="cms-shell">
    <aside className={`cms-sidebar ${mobileNav?"open":""}`}><div className="cms-brand"><Image src="/logo.jpeg" alt="US GLOBAL IMPEX" width={104} height={60} priority/><small>CONTENT HUB</small><button onClick={()=>setMobileNav(false)}><X/></button></div><nav><p>WEBSITE MANAGEMENT</p>{sections.map((section)=>{const Icon=section.icon;return <button key={section.id} className={active.id===section.id?"active":""} onClick={()=>{setActive(section);setMobileNav(false)}}><Icon size={19}/><span>{section.label}</span><ChevronRight size={15}/></button>})}</nav><div className="cms-sidebar-foot"><a href="/" target="_blank"><Globe2 size={17}/>View live website</a><button onClick={logout}><LogOut size={17}/>Sign out</button></div></aside>
    <section className="cms-workspace"><header className="cms-topbar"><button className="cms-mobile-menu" onClick={()=>setMobileNav(true)}><LayoutDashboard/></button><div><p>CONTENT MANAGEMENT</p><h1>{active.label}</h1></div><div className="cms-user"><span>UA</span><div><strong>US GLOBAL IMPEX Administrator</strong><small>Content manager</small></div></div></header>
      <div className="cms-body">{!active.single&&<aside className="cms-entry-list"><div><strong>{active.label}</strong><button onClick={createNew}><Plus size={17}/>New</button></div>{loading?<p className="cms-muted">Loading…</p>:items.map(item=><button key={item.documentId} className={selected?.documentId===item.documentId?"active":""} onClick={()=>choose(item)}><span>{titleOf(item,active)}</span><small>{item.category||item.location||item.slug||"Published"}</small></button>)}</aside>}
        <div className="cms-editor">{loading?<div className="cms-loading">Loading content…</div>:<><div className="cms-editor-head"><div><p>{selected?"EDIT PUBLISHED CONTENT":"CREATE NEW ENTRY"}</p><h2>{titleOf(form,active)}</h2></div><div>{!active.single&&selected&&<button className="cms-delete" onClick={remove}><Trash2 size={17}/></button>}<button className="cms-save" onClick={save} disabled={saving}><Save size={17}/>{saving?"Saving…":"Save & publish"}</button></div></div>{notice&&<div className={`cms-notice ${notice.includes("saved")?"success":""}`}>{notice}</div>}
          <div className="cms-form">{groups.map(([group,groupFields])=><fieldset key={group}><legend>{group}</legend><div className="cms-field-grid">{groupFields.map(field=><Field key={field.name} field={field} value={form[field.name]} setValue={(value)=>setForm({...form,[field.name]:value})} upload={(file)=>upload(field,file)}/>)}</div></fieldset>)}</div></>}
        </div></div>
    </section>
  </main>;
}

function Field({field,value,setValue,upload}){
  const wide=["textarea","json","image"].includes(field.type);
  if(field.type==="boolean")return <label className="cms-field cms-toggle"><span>{field.label}</span><button type="button" className={value?"on":""} onClick={()=>setValue(!value)}><i/></button><small>{value?"Enabled":"Disabled"}</small></label>;
  if(field.type==="image")return <label className="cms-field cms-field-wide"><span>{field.label}</span><div className="cms-image-field">{value?.url?<Image src={`${value.url.startsWith("http")?"":publicCmsUrl}${value.url}`} alt="" width={135} height={82} unoptimized/>:<div><ImagePlus/><small>No image selected</small></div>}<label><ImagePlus size={17}/>Upload image<input type="file" accept="image/*" onChange={(event)=>upload(event.target.files?.[0])}/></label>{value&&<button type="button" onClick={()=>setValue(null)}>Remove</button>}</div></label>;
  const shown=field.type==="json"?(typeof value==="string"?value:JSON.stringify(value??[],null,2)):(value??"");
  return <label className={`cms-field ${wide?"cms-field-wide":""}`}><span>{field.label}</span>{field.type==="textarea"||field.type==="json"?<textarea rows={field.type==="json"?7:4} value={shown} onChange={(e)=>setValue(e.target.value)}/>:<input type={field.type} value={shown} onChange={(e)=>setValue(field.type==="number"?Number(e.target.value):e.target.value)}/>}</label>;
}
